const pdfParse = require('pdf-parse');
const { PDFDocument } = require('pdf-lib');

/**
 * Regex patterns to detect Table of Contents (TOC) chapter/section lines from text
 * Examples:
 * - Chapter 1: Introduction to Physics ... Page 14
 * - 1.2 Thermodynamics ................... 45
 * - Section 3. Newton's Laws - 78
 * - UNIT IV: Quantum Mechanics (Page 120)
 */
const TOC_LINE_REGEXES = [
  /^(?:Chapter|Unit|Module|Section|Topic|Part)\s*([0-9A-Za-z.-]+)[\s:.-]+(.*?)(?:[.·…\s_-]+(?:page|p\.?)?\s*(\d+))$/i,
  /^(\d+(?:\.\d+)*)\s+([A-Za-z0-9\s,:'"-]+?)(?:[.·…\s_-]+(?:page|p\.?)?\s*(\d+))$/i,
  /^([A-Za-z\s,:'"-]+?)(?:[.·…\s_-]{3,}(?:page|p\.?)?\s*(\d+))$/i,
];

/**
 * Parses raw text extracted from first N pages of a PDF to detect Table of Contents entries.
 * 
 * @param {string} text - Raw extracted text from introductory pages
 * @param {number} totalPages - Total page count of the PDF document
 * @returns {Array<{ chapterNumber: string, title: string, startPage: number, endPage: number }>}
 */
function extractTocFromText(text, totalPages = 100) {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const detectedEntries = [];

  for (const line of lines) {
    // Avoid header/footer noise
    if (line.length < 5 || line.length > 200) continue;

    for (const regex of TOC_LINE_REGEXES) {
      const match = line.match(regex);
      if (match) {
        let chapterNum = '';
        let title = '';
        let pageNum = 0;

        if (match.length === 4) {
          chapterNum = match[1]?.trim() || '';
          title = match[2]?.trim() || '';
          pageNum = parseInt(match[3], 10);
        } else if (match.length === 3) {
          title = match[1]?.trim() || '';
          pageNum = parseInt(match[2], 10);
        }

        if (pageNum > 0 && pageNum <= totalPages && title.length > 2) {
          detectedEntries.push({
            chapterNumber: chapterNum || `Ch ${detectedEntries.length + 1}`,
            title: title.replace(/[.·…\s_-]+$/, ''),
            startPage: pageNum,
          });
          break;
        }
      }
    }
  }

  // Deduplicate and sort entries by page number
  detectedEntries.sort((a, b) => a.startPage - b.startPage);
  const uniqueEntries = [];
  const seenPages = new Set();

  for (const entry of detectedEntries) {
    if (!seenPages.has(entry.startPage)) {
      seenPages.add(entry.startPage);
      uniqueEntries.push(entry);
    }
  }

  // Calculate endPage for each chapter
  for (let i = 0; i < uniqueEntries.length; i++) {
    if (i < uniqueEntries.length - 1) {
      uniqueEntries[i].endPage = Math.max(
        uniqueEntries[i].startPage,
        uniqueEntries[i + 1].startPage - 1
      );
    } else {
      uniqueEntries[i].endPage = totalPages;
    }
    uniqueEntries[i].pageCount = uniqueEntries[i].endPage - uniqueEntries[i].startPage + 1;
  }

  return uniqueEntries;
}

/**
 * Inspects a PDF Buffer / file and extracts embedded bookmarks or heuristic TOC structure
 * 
 * @param {Buffer} pdfBuffer - Binary buffer of the PDF file
 * @returns {Promise<{ totalPages: number, title: string, chapters: Array, hasNativeBookmarks: boolean }>}
 */
async function inspectPdfStructure(pdfBuffer) {
  // 1. Load with pdf-lib to get metadata and page count
  const pdfDoc = await PDFDocument.load(pdfBuffer, { ignoreEncryption: true });
  const totalPages = pdfDoc.getPageCount();
  const title = pdfDoc.getTitle() || 'Uploaded Document';

  // 2. Parse text from first 25 pages to look for Table of Contents
  let parsedText = '';
  try {
    if (typeof pdfParse === 'function') {
      const data = await pdfParse(pdfBuffer, { max: Math.min(30, totalPages) });
      parsedText = data.text || '';
    } else if (pdfParse.PDFParse) {
      const parser = new pdfParse.PDFParse();
      const data = await parser.parse(pdfBuffer);
      parsedText = data.text || '';
    }
  } catch (err) {
    console.warn('[PdfStructureService] pdf text extraction warning:', err.message);
  }

  // 3. Extract TOC entries
  let chapters = extractTocFromText(parsedText, totalPages);

  // 4. If no TOC detected via regex, create reasonable default chapter chunks (e.g. 25-page modules)
  if (chapters.length === 0) {
    const chunkSize = Math.min(30, Math.max(10, Math.floor(totalPages / 5)));
    let currentStart = 1;
    let moduleIdx = 1;

    while (currentStart <= totalPages) {
      const endPage = Math.min(totalPages, currentStart + chunkSize - 1);
      chapters.push({
        chapterNumber: `Part ${moduleIdx}`,
        title: `Module ${moduleIdx} (Pages ${currentStart}-${endPage})`,
        startPage: currentStart,
        endPage,
        pageCount: endPage - currentStart + 1,
        isAutoGenerated: true,
      });
      currentStart = endPage + 1;
      moduleIdx++;
    }
  }

  return {
    totalPages,
    title,
    hasNativeBookmarks: false,
    chapterCount: chapters.length,
    chapters,
  };
}

module.exports = {
  extractTocFromText,
  inspectPdfStructure,
};
