version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: openprep-prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: openprep-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=openprep_admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring-net

  tempo:
    image: grafana/tempo:latest
    container_name: openprep-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    restart: unless-stopped
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    networks:
      - monitoring-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: openprep-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: unless-stopped
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Otel collector internal metrics
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tempo
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
