const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');

/**
 * FlashcardMasterySnapshot — periodic snapshots of flashcard mastery state.
 *
 * Captures retention rates, forgetting curve projections, review efficiency,
 * and per-deck mastery levels. Generated by the mastery service on demand or
 * via scheduled job. Used by the frontend for dashboard charts and by the
 * review scheduler to prioritise which cards to surface first.
 */
const FlashcardMasterySnapshot = sequelize.define(
  'FlashcardMasterySnapshot',
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    user: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    snapshotDate: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },

    // ── Global Metrics ──────────────────────────────────────────────────
    totalCards: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    reviewedToday: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },
    reviewStreak: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Consecutive days with at least one review',
    },
    overallRetentionRate: {
      type: DataTypes.FLOAT,
      defaultValue: 0,
      comment: 'Percentage of cards recalled correctly across all reviews',
    },
    averageInterval: {
      type: DataTypes.FLOAT,
      defaultValue: 0,
      comment: 'Average SM-2 interval across all cards in days',
    },
    averageEfactor: {
      type: DataTypes.FLOAT,
      defaultValue: 2.5,
      comment: 'Average SM-2 easiness factor across all cards',
    },
    totalReviews: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
    },

    // ── Forgetting Curve ────────────────────────────────────────────────
    cardsAtRisk: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Cards likely to be forgotten within 24 hours',
    },
    cardsOverdue: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Cards past their nextReviewDate',
    },
    predictedForgettingCurve: {
      type: DataTypes.JSONB,
      defaultValue: [],
      comment: 'Array of { day, retentionPercent } for next 14 days',
    },
    retentionDistribution: {
      type: DataTypes.JSONB,
      defaultValue: {},
      comment: 'Map of retention bucket (0-20, 20-40, etc.) -> card count',
    },

    // ── Mastery Levels ──────────────────────────────────────────────────
    masteryBreakdown: {
      type: DataTypes.JSONB,
      defaultValue: {},
      comment: 'Map of mastery level -> { count, percentage }',
    },
    newCards: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Cards with 0 reviews',
    },
    learningCards: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Cards with 1-3 reviews and efactor < 2.5',
    },
    matureCards: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      comment: 'Cards with interval >= 21 days',
    },

    // ── Per-Subject/Deck Breakdown ──────────────────────────────────────
    deckMastery: {
      type: DataTypes.JSONB,
      defaultValue: {},
      comment: 'Map of deckId -> { name, totalCards, retentionRate, averageInterval, masteryScore }',
    },
    subjectMastery: {
      type: DataTypes.JSONB,
      defaultValue: {},
      comment: 'Map of subjectId -> { name, totalCards, retentionRate, averageInterval }',
    },

    // ── Review Efficiency ───────────────────────────────────────────────
    reviewEfficiency: {
      type: DataTypes.FLOAT,
      defaultValue: 0,
      comment: '0-100 score based on how well intervals align with retention',
    },
    optimalReviewWindow: {
      type: DataTypes.JSONB,
      defaultValue: null,
      comment: '{ start, end } hours when user reviews most effectively',
    },

    // ── Recommendations ─────────────────────────────────────────────────
    topCardsForReview: {
      type: DataTypes.JSONB,
      defaultValue: [],
      comment: 'Array of { cardId, front, urgency, subject } for prioritised review queue',
    },
    recommendations: {
      type: DataTypes.JSONB,
      defaultValue: [],
      comment: 'Array of { category, message, impact } objects',
    },

    // ── Metadata ────────────────────────────────────────────────────────
    metadata: {
      type: DataTypes.JSONB,
      defaultValue: {},
    },
  },
  {
    timestamps: true,
    indexes: [
      {
        name: 'flashcardmastery_user_date_idx',
        fields: ['user', 'snapshotDate'],
      },
      {
        name: 'flashcardmastery_user_created_idx',
        fields: ['user', 'createdAt'],
      },
    ],
  }
);

module.exports = FlashcardMasterySnapshot;
